<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Commerce.Domain\Commerce.Domain.csproj" />
    <ProjectReference Include="..\..\src\Commerce.Application\Commerce.Application.csproj" />
    <ProjectReference Include="..\..\src\Commerce.BranchNode\Commerce.BranchNode.csproj" />
    <ProjectReference Include="..\..\src\Commerce.Cloud.Api\Commerce.Cloud.Api.csproj" />
    <ProjectReference Include="..\..\src\Commerce.Web\Commerce.Web.csproj" />
    <ProjectReference Include="..\..\src\Commerce.Pos.Windows\Commerce.Pos.Windows.csproj" />
  </ItemGroup>

</Project>
