-- Vaca Verde master data seed: cities, business types and customers.
--
-- GENERATED by generate_seed.py from the normalized spreadsheets - do not edit
-- by hand; see README.md in this directory. Contains REAL customer data (owner
-- decision), applied after the organization is provisioned.
--
-- Safe to re-run: every row has a deterministic id and is inserted with
-- ON CONFLICT DO NOTHING, so a second run changes nothing and never overwrites
-- later edits. When the organization "Vaca Verde" (or its business admin) does
-- not exist yet, the file prints a NOTICE and changes nothing.
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 001_vaca_verde_master_data.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the customers.';
        RETURN;
    END IF;

    INSERT INTO _vv_seed_ctx (organization_id, user_id) VALUES (v_org, v_user);
END $$;

-- Cities: the 23 reference rows keep their original id and audit dates;
-- new ones get a deterministic id and the current time.
INSERT INTO cities (id, organization_id, name, key, sort_order, is_active, created_at_utc, updated_at_utc)
SELECT COALESCE(v.id::uuid, md5('vaca-verde:city:' || v.key)::uuid), c.organization_id, v.name, v.key,
       v.sort_order::integer, v.is_active::boolean,
       COALESCE(v.created_at::timestamptz, now()), COALESCE(v.updated_at::timestamptz, now())
FROM (VALUES
    ('56f6a18c-db9b-45f9-9ddc-a4b553de11ce', 'Arrecifes', 'arrecifes', 1, 'true', '2026-01-10 03:42:10.624908+00', '2026-03-09 14:18:21.962+00'),
    ('606d6ace-90a8-4a69-9f29-87a27de1bee5', 'Baradero', 'baradero', 2, 'true', '2026-01-10 04:28:40.615434+00', '2026-01-17 19:34:39.42+00'),
    ('ba8a2289-4a10-4b37-b0a4-2f869c78cfa1', 'San Pedro', 'san_pedro', 3, 'true', '2026-01-10 04:28:56.759963+00', '2026-01-10 04:28:56.849+00'),
    ('e310e7bb-2ce8-4b3a-af81-1b745cde7e31', 'Pérez Millán', 'perez_millan', 4, 'true', '2026-01-10 04:29:30.60028+00', '2026-01-10 04:29:30.688+00'),
    ('b23807f6-a666-4328-970b-25a2298fc8d6', 'Salto', 'salto', 5, 'true', '2026-01-10 04:29:38.35929+00', '2026-01-10 04:29:38.454+00'),
    ('9e910d35-32f4-4454-b99a-5353145fa1fb', 'Carmen de Areco', 'carmen_de_areco', 6, 'true', '2026-01-10 04:29:52.358674+00', '2026-01-10 04:29:52.463+00'),
    ('9312c672-b725-429b-aac5-8c701a40258f', 'Capitán Sarmiento', 'capitan_sarmiento', 7, 'true', '2026-01-10 04:30:02.811173+00', '2026-01-10 04:30:02.917+00'),
    ('c7038e7d-64c8-4c0b-878b-3e691328c05b', 'San Antonio de Areco', 'san_antonio_de_areco', 8, 'true', '2026-01-10 04:30:47.380782+00', '2026-01-10 04:30:47.474+00'),
    ('500f035e-a0ad-4404-ab25-5eb8af8fdd17', 'Santa Lucía', 'santa_lucia', 9, 'true', '2026-01-10 04:31:04.315256+00', '2026-01-10 04:31:04.399+00'),
    ('09aa880f-8529-475c-9a42-7d5af88ac0eb', 'Pergamino', 'pergamino', 10, 'true', '2026-01-10 04:31:25.105515+00', '2026-01-10 04:31:25.216+00'),
    ('e962c9ee-2c78-4cb4-b4c0-ba0a9e9a3746', 'Doyle', 'doyle', 11, 'true', '2026-01-10 04:34:53.115691+00', '2026-01-10 04:34:52.505+00'),
    ('d61c888f-59a0-4422-a5eb-80e932987410', 'Capital Federal', 'capital_federal', 12, 'true', '2026-02-09 22:39:17.820904+00', '2026-02-09 22:39:15.901+00'),
    ('7bdf7a66-fbc6-40af-b18d-789dc0e605d7', 'Chacabuco', 'chacabuco', 13, 'true', '2026-02-09 22:39:41.700997+00', '2026-02-09 22:39:39.831+00'),
    ('5909ef61-1c38-4b76-a57d-6cc08807af95', 'La Plata', 'la_plata', 14, 'true', '2026-02-09 22:39:56.120377+00', '2026-02-09 22:39:54.273+00'),
    ('4ccfaebe-88c7-4ed1-948c-f044693fe46c', 'Rojas', 'rojas', 15, 'true', '2026-02-09 22:40:28.184044+00', '2026-02-09 22:40:26.351+00'),
    ('b1cc840e-e4b3-411e-a33d-fa41382ddd00', 'Santiago del Estero', 'santiago_del_estero', 16, 'true', '2026-02-09 22:40:47.126011+00', '2026-02-09 22:40:45.293+00'),
    ('8bdc1736-3569-4679-9dcd-f5bffbb0b456', 'San Andrés de Giles', 'san_andres_de_giles', 17, 'true', '2026-02-09 22:40:55.692797+00', '2026-02-09 22:40:53.851+00'),
    ('e941a9d3-8707-43b2-8794-19e8d8d00456', 'Urquiza', 'urquiza', 18, 'true', '2026-03-03 19:54:22.295565+00', '2026-03-03 19:54:24.279+00'),
    ('ea25e669-719f-4274-89bc-3d500a50da5d', 'Inés Indart', 'ines_indart', 19, 'true', '2026-03-13 14:17:49.646917+00', '2026-03-13 14:17:51.731+00'),
    ('28a44a67-510d-43bd-baa4-d8d17b175697', 'Ramallo', 'ramallo', 20, 'true', '2026-04-28 18:48:17.100118+00', '2026-04-28 18:48:17.609+00'),
    ('e6af0b3b-6576-4d12-bb8f-29e7e5935efd', 'Córdoba', 'cordoba', 21, 'true', '2026-05-04 18:35:20.628119+00', '2026-05-04 18:35:21.874+00'),
    ('829c0d40-4757-4186-be54-d51cbb4ef382', 'Zárate', 'zarate', 22, 'true', '2026-05-12 21:26:58.267011+00', '2026-05-12 21:26:58.035+00'),
    ('09a86fa3-9da6-4703-bd48-0e15c3092556', 'Arroyo Dulce', 'arroyo_dulce', 23, 'true', '2026-06-19 15:00:10.801892+00', '2026-06-19 15:00:14.24+00'),
    (NULL, 'Río Tala', 'rio_tala', 24, 'true', NULL, NULL),
    (NULL, 'San Nicolás', 'san_nicolas', 25, 'true', NULL, NULL)
) AS v (id, name, key, sort_order, is_active, created_at, updated_at)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;

-- Business types.
INSERT INTO business_types (id, organization_id, name, key, sort_order)
SELECT md5('vaca-verde:business-type:' || v.key)::uuid, c.organization_id, v.name, v.key, v.sort_order::integer
FROM (VALUES
    ('Almacén', 'almacen', '1'),
    ('Bodegón', 'bodegon', '2'),
    ('Carnicería', 'carniceria', '3'),
    ('Carrito', 'carrito', '4'),
    ('Estación de Servicio', 'estacion_de_servicio', '5'),
    ('Parrilla', 'parrilla', '6'),
    ('Pollería', 'polleria', '7'),
    ('Resto Bar', 'resto_bar', '8'),
    ('Rotisería', 'rotiseria', '9'),
    ('Sanguchería', 'sangucheria', '10'),
    ('Supermercado', 'supermercado', '11')
) AS v (name, key, sort_order)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;

-- Customers (Wholesale, enabled). The id derives from `key` (name + city slug).
INSERT INTO customers (id, organization_id, customer_kind, display_name, contact_name, address_street, phone,
                       city_id, business_type_id, tax_id_type, tax_id, notes, is_enabled, created_by_user_id)
SELECT md5('vaca-verde:customer:' || v.key)::uuid, c.organization_id, 'Wholesale', v.display_name, v.contact_name,
       v.address_street, v.phone, ci.id, bt.id, v.tax_id_type, v.tax_id, v.notes, true, c.user_id
FROM (VALUES
    ('adan-rito-pontaquarto', 'Adan Rito Pontaquarto', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20338138874', NULL),
    ('al-toque--capitan_sarmiento', 'Al Toque', 'Lucas Badano', NULL, '2478476538', 'capitan_sarmiento', 'rotiseria', 'None', NULL, 'También: Parrilla'),
    ('almacen-cristian--arrecifes', 'Almacén Cristian', NULL, 'Av. Cordoba', '2478466104', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('almacen-esteban--arrecifes', 'Almacén Esteban', 'Esteban', 'Brasil 1132', '2478408929', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('almacen-ferreti--arrecifes', 'Almacén Ferreti', NULL, 'F Cancha Hurac', '2478502607', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('almacen-karina--arrecifes', 'Almacén Karina', 'Karina', 'Av. Belgrano', '2478518580', 'arrecifes', 'almacen', 'None', NULL, 'También: Pollería'),
    ('antonella-ulujan-rolandi', 'Antonella Uluján Rolandi', NULL, NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('ariel-padre--san_nicolas', 'Ariel Padre', NULL, 'Avenida ?', '3364612756', 'san_nicolas', NULL, 'None', NULL, NULL),
    ('autoservicio-arrecifes--arrecifes', 'Autoservicio Arrecifes', NULL, 'Palermo R. Rojas', '2478520672', 'arrecifes', 'supermercado', 'None', NULL, NULL),
    ('balthazar--san_antonio_de_areco', 'Balthazar', 'Martin', NULL, '1154190141', 'san_antonio_de_areco', 'resto_bar', 'None', NULL, NULL),
    ('bambini--arrecifes', 'Bambini', 'Laura', NULL, '1130099695', 'arrecifes', 'resto_bar', 'None', NULL, NULL),
    ('bar-plaza--arrecifes', 'Bar Plaza', 'Celeste', 'Rivadavia y R Gutier', '2478462532', 'arrecifes', 'resto_bar', 'None', NULL, NULL),
    ('baratini--capitan_sarmiento', 'Baratini', NULL, NULL, NULL, 'capitan_sarmiento', 'carniceria', 'None', NULL, 'Especificación original: CARNIC "LA MARCA"'),
    ('belen-club-river--arrecifes', 'Belen Club River', 'Belen', NULL, '2478466174', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('berges--capitan_sarmiento', 'Berges', 'Bernardo', NULL, NULL, 'capitan_sarmiento', NULL, 'None', NULL, NULL),
    ('bodegon--capitan_sarmiento', 'Bodegón', 'Gaston', NULL, NULL, 'capitan_sarmiento', 'resto_bar', 'None', NULL, 'También: Bodegón'),
    ('cantabria--arrecifes', 'Cantabria', 'Ani', 'Av. Merlassino', '2478520758', 'arrecifes', 'resto_bar', 'None', NULL, NULL),
    ('carlos-dario-sabino', 'Carlos Darío Sabino', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20173783648', NULL),
    ('carniceria--capitan_sarmiento', 'Carnicería', 'Joaquin', NULL, NULL, 'capitan_sarmiento', 'carniceria', 'None', NULL, NULL),
    ('carniceria-baez--san_antonio_de_areco', 'Carnicería Baez', 'Ignacio', NULL, '3329525117', 'san_antonio_de_areco', 'carniceria', 'None', NULL, NULL),
    ('carrito-alta-pinta--arrecifes', 'Carrito Alta Pinta', NULL, NULL, '2478410391', 'arrecifes', 'carrito', 'None', NULL, NULL),
    ('carrito-cacho--arrecifes', 'Carrito Cacho', NULL, NULL, '2478477034', 'arrecifes', 'carrito', 'None', NULL, NULL),
    ('carrito-don-lolo--arrecifes', 'Carrito Don Lolo', NULL, NULL, '2478502520', 'arrecifes', 'carrito', 'None', NULL, NULL),
    ('carrito-franco-rios--arrecifes', 'Carrito Franco Rios', NULL, NULL, '2478466029', 'arrecifes', 'carrito', 'None', NULL, NULL),
    ('chuanyan-he', 'Chuanyan He', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20940518548', NULL),
    ('cliente-coti--capitan_sarmiento', 'Cliente Coti', NULL, NULL, NULL, 'capitan_sarmiento', 'carniceria', 'None', NULL, NULL),
    ('coti--salto', 'Coti', NULL, 'Arredondo 167', '2474683008', 'salto', NULL, 'None', NULL, NULL),
    ('crisol--arrecifes', 'Crisol', 'Tola', NULL, '2478542341', 'arrecifes', 'parrilla', 'None', NULL, NULL),
    ('damian-parrilla--capitan_sarmiento', 'Damian Parrilla', 'Damian', NULL, '2478496220', 'capitan_sarmiento', 'parrilla', 'None', NULL, NULL),
    ('derlis-tomas-riva', 'Derlis Tomás Riva', NULL, NULL, NULL, NULL, 'carniceria', 'None', NULL, NULL),
    ('despensa-tiki-tiki--arrecifes', 'Despensa Tiki Tiki', NULL, NULL, '2478469397', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('diego-ortiz--capitan_sarmiento', 'Diego Ortiz', 'Diego', NULL, '2478514837', 'capitan_sarmiento', NULL, 'None', NULL, NULL),
    ('eduardo-karina--arrecifes', 'Eduardo (Karina)', 'Eduardo', NULL, '2478509566', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('el-condor--san_pedro', 'El Condor', 'Felipe', NULL, '3329696757', 'san_pedro', 'carniceria', 'None', NULL, NULL),
    ('el-guti--arrecifes', 'El Guti', 'Mirko', 'R. Gutierrez', '2478402431', 'arrecifes', 'resto_bar', 'None', NULL, NULL),
    ('el-mono--arrecifes', 'El Mono', 'Carlitos', 'Alberdi', '2478543711', 'arrecifes', 'almacen', 'None', NULL, NULL),
    ('el-tata--capitan_sarmiento', 'El Tata', 'Iris', NULL, '2325689453', 'capitan_sarmiento', 'parrilla', 'None', NULL, NULL),
    ('entre-panes--arrecifes', 'Entre Panes', 'Gonza', NULL, '2478465824', 'arrecifes', 'sangucheria', 'None', NULL, NULL),
    ('facundo-d-valle--arrecifes', 'Facundo D Valle', 'Facu', NULL, '2478460750', 'arrecifes', 'polleria', 'None', NULL, NULL),
    ('herrera-mauricio-eugenio', 'Herrera Mauricio Eugenio', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20315384088', NULL),
    ('javier--baradero', 'Javier', NULL, 'Ruta 9', NULL, 'baradero', NULL, 'None', NULL, NULL),
    ('javier-salvador-kapp', 'Javier Salvador Kapp', NULL, NULL, NULL, NULL, 'carniceria', 'Cuit', '20284364156', NULL),
    ('jormer--arrecifes', 'Jormer', NULL, 'S H Perez y P Sard', '2478507746', 'arrecifes', NULL, 'None', NULL, NULL),
    ('jose-maria-bogarin--san_antonio_de_areco', 'José María Bogarín', NULL, NULL, NULL, 'san_antonio_de_areco', 'carniceria', 'Cuit', '20275555739', NULL),
    ('jose-maria-esperanza', 'José María Esperanza', NULL, NULL, NULL, NULL, 'carniceria', 'Dni', '27015956', NULL),
    ('juan-domingo-figueroa--salto', 'Juan Domingo Figueroa', NULL, NULL, NULL, 'salto', 'carniceria', 'Cuit', '20241371825', NULL),
    ('juan-porcel--arrecifes', 'Juan Porcel', 'Juan', NULL, '2478403624', 'arrecifes', 'carniceria', 'None', NULL, NULL),
    ('karen-lucia-leguizamon', 'Karen Lucia Leguizamon', NULL, NULL, NULL, NULL, NULL, 'Dni', '40998413', NULL),
    ('la-cuadra--capitan_sarmiento', 'La Cuadra', NULL, NULL, '2478441520', 'capitan_sarmiento', 'resto_bar', 'None', NULL, NULL),
    ('la-picasa--baradero', 'La Picasa', 'Javier', NULL, '3329691185', 'baradero', 'parrilla', 'None', NULL, NULL),
    ('la-rosita--san_antonio_de_areco', 'La Rosita', NULL, NULL, '1140444036', 'san_antonio_de_areco', NULL, 'None', NULL, NULL),
    ('la-sapiola--san_antonio_de_areco', 'La Sapiola', 'Hernan', NULL, '2304553227', 'san_antonio_de_areco', 'resto_bar', 'None', NULL, NULL),
    ('las-amalias--san_pedro', 'Las Amalias', 'Walter', NULL, '3329626661', 'san_pedro', 'parrilla', 'None', NULL, NULL),
    ('lo-de-rueda--arrecifes', 'Lo de Rueda', 'Martin', NULL, '3407415701', 'arrecifes', 'resto_bar', 'None', NULL, 'También: Parrilla'),
    ('locos-de-asar--arrecifes', 'Locos de Asar', 'Tito', 'Av. R. Saenz P.', '2478506450', 'arrecifes', 'parrilla', 'None', NULL, NULL),
    ('los-abraham--san_pedro', 'Los Abraham', 'Luis', NULL, '3329625588', 'san_pedro', 'parrilla', 'None', NULL, NULL),
    ('los-abraham-luis--rio_tala', 'Los Abraham Luis', NULL, NULL, NULL, 'rio_tala', NULL, 'None', NULL, NULL),
    ('luis-figueroa--salto', 'Luis Figueroa', NULL, NULL, NULL, 'salto', 'carniceria', 'None', NULL, NULL),
    ('luis-gallo--capitan_sarmiento', 'Luis Gallo', NULL, NULL, '2478420011', 'capitan_sarmiento', NULL, 'None', NULL, NULL),
    ('machello-luciano-noel--chacabuco', 'Machello Luciano Noel', NULL, 'Buenos Aires y Zapiola', NULL, 'chacabuco', 'carniceria', 'Cuit', '20276231961', NULL),
    ('maria-vanesa-diaz', 'María Vanesa Díaz', NULL, NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('mario-alvarez--capitan_sarmiento', 'Mario Alvarez', NULL, NULL, NULL, 'capitan_sarmiento', 'carniceria', 'None', NULL, NULL),
    ('martin-super-jardin--pergamino', 'Martin Super Jardin', NULL, 'Av. Principal', '2477316656', 'pergamino', 'supermercado', 'None', NULL, NULL),
    ('martinez-santiago--salto', 'Martínez Santiago', NULL, 'San Pablo y Bolívar', NULL, 'salto', NULL, 'Cuit', '23327154699', NULL),
    ('mingo-alfaro--arrecifes', 'Mingo Alfaro', 'Mingo', 'Urquiza', NULL, 'arrecifes', 'polleria', 'None', NULL, NULL),
    ('miunoz-pipi--arrecifes', 'Miuñoz-Pipi', 'Walter', NULL, '2478409233', 'arrecifes', 'almacen', 'None', NULL, 'También: Carrito'),
    ('nestor-bilbao--arrecifes', 'Nestor Bilbao', 'Nestor', 'Palermo', '2478461601', 'arrecifes', 'carniceria', 'None', NULL, 'También: Almacén'),
    ('nicolas-eduardo-pagano', 'Nicolás Eduardo Pagano', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20314134681', NULL),
    ('palmieri-federico-hernan', 'Palmieri Federico Hernán', NULL, NULL, NULL, NULL, NULL, 'Dni', '25137726', NULL),
    ('parrilla-avanti--san_antonio_de_areco', 'Parrilla Avanti', 'Remigio', NULL, '2325519316', 'san_antonio_de_areco', 'parrilla', 'None', NULL, NULL),
    ('parrilla-caio--pergamino', 'Parrilla Caio', NULL, 'Ruta', '2477453141', 'pergamino', 'parrilla', 'None', NULL, NULL),
    ('parrilla-don-manuel--san_antonio_de_areco', 'Parrilla Don Manuel', NULL, 'Ruta 8 (Vieja)', '2326403064', 'san_antonio_de_areco', 'parrilla', 'None', NULL, NULL),
    ('parrilla-javier--baradero', 'Parrilla Javier', 'Javier Bargas', 'Ruta 9', '3329627731', 'baradero', 'parrilla', 'None', NULL, NULL),
    ('parrilla-los-pinos--capitan_sarmiento', 'Parrilla Los Pinos', 'Natalia', NULL, '2478556809', 'capitan_sarmiento', 'parrilla', 'None', NULL, NULL),
    ('patricia-biela--arrecifes', 'Patricia Biela', NULL, 'Ruta 8 y 51', '2478556572', 'arrecifes', NULL, 'None', NULL, NULL),
    ('peralta-oscar--capitan_sarmiento', 'Peralta Oscar', NULL, 'Av. Alem y Corrientes', '2478463463', 'capitan_sarmiento', NULL, 'None', NULL, NULL),
    ('pillado-joaquin', 'Pillado Joaquín', NULL, NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('pyp--arrecifes', 'PyP', 'Pelusa', NULL, '2478409302', 'arrecifes', 'rotiseria', 'None', NULL, NULL),
    ('ramiro-paz', 'Ramiro Paz', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20334104169', NULL),
    ('rene-alberto-caviglia', 'René Alberto Caviglia', NULL, NULL, NULL, NULL, NULL, 'Cuit', '20106630578', NULL),
    ('segundo-valloire--salto', 'Segundo Valloire', NULL, NULL, NULL, 'salto', 'carniceria', 'Dni', '30308717', NULL),
    ('serafina-david--arrecifes', 'Serafina David', NULL, 'España y Moreno', '2478466796', 'arrecifes', NULL, 'None', NULL, NULL),
    ('shell-sarmiento--capitan_sarmiento', 'Shell Sarmiento', 'Sebastian', NULL, '1136303440', 'capitan_sarmiento', 'estacion_de_servicio', 'None', NULL, NULL),
    ('super-baez--san_antonio_de_areco', 'Super Baez', 'Juan Ignacio', NULL, '3487707061', 'san_antonio_de_areco', 'supermercado', 'None', NULL, NULL),
    ('turco-guillermo--arrecifes', 'Turco Guillermo', NULL, 'Fonavi', NULL, 'arrecifes', NULL, 'None', NULL, NULL),
    ('valeria-resto--arrecifes', 'Valeria Resto', 'Carlitos', 'Av. Sarmiento', '2478503181', 'arrecifes', 'resto_bar', 'None', NULL, NULL),
    ('willie-carniceria--capitan_sarmiento', 'Willie Carnicería', NULL, '(Fonavi/El Campeon)', '3415785507', 'capitan_sarmiento', 'carniceria', 'None', NULL, 'Especificación original: Súper Campeones')
) AS v (key, display_name, contact_name, address_street, phone, city_key, business_type_key, tax_id_type, tax_id, notes)
CROSS JOIN _vv_seed_ctx c
LEFT JOIN cities ci ON ci.organization_id = c.organization_id AND ci.key = v.city_key
LEFT JOIN business_types bt ON bt.organization_id = c.organization_id AND bt.key = v.business_type_key
ON CONFLICT DO NOTHING;

COMMIT;
