-- Vaca Verde master data seed: business types, customers and their contacts.
--
-- GENERATED by generate_seed.py from the normalized spreadsheets - do not edit
-- by hand; see README.md in this directory. Contains REAL customer data (owner
-- decision), applied after the organization is provisioned.
--
-- Cities are NOT created here: they are global core geography (migration 0028,
-- Georef). Customers reference a Georef locality by its INDEC id, and the
-- original audit dates of the owner's cities are restored on those global rows
-- when nobody has touched them since they were loaded.
--
-- Safe to re-run: every row has a deterministic id and is inserted with
-- ON CONFLICT DO NOTHING, so a second run changes nothing and never overwrites
-- later edits. When the organization "Vaca Verde" (or its business admin) does
-- not exist yet, the file prints a NOTICE and changes nothing.
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 001_vaca_verde_master_data.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the customers.';
        RETURN;
    END IF;

    INSERT INTO _vv_seed_ctx (organization_id, user_id) VALUES (v_org, v_user);
END $$;

-- Cities are global (Georef, migration 0028). Restore the owner's original audit dates
-- on the matching rows, only while they still carry the load time (never over later edits).
UPDATE cities g
SET created_at_utc = v.created_at::timestamptz, updated_at_utc = v.updated_at::timestamptz
FROM (VALUES
    ('06077010', '2026-01-10 03:42:10.624908+00', '2026-03-09 14:18:21.962+00'),
    ('06070010', '2026-01-10 04:28:40.615434+00', '2026-01-17 19:34:39.42+00'),
    ('06770050', '2026-01-10 04:28:56.759963+00', '2026-01-10 04:28:56.849+00'),
    ('06665030', '2026-01-10 04:29:30.60028+00', '2026-01-10 04:29:30.688+00'),
    ('06714060', '2026-01-10 04:29:38.35929+00', '2026-01-10 04:29:38.454+00'),
    ('06161010', '2026-01-10 04:29:52.358674+00', '2026-01-10 04:29:52.463+00'),
    ('06140010', '2026-01-10 04:30:02.811173+00', '2026-01-10 04:30:02.917+00'),
    ('06735020', '2026-01-10 04:30:47.380782+00', '2026-01-10 04:30:47.474+00'),
    ('06770060', '2026-01-10 04:31:04.315256+00', '2026-01-10 04:31:04.399+00'),
    ('06623100', '2026-01-10 04:31:25.105515+00', '2026-01-10 04:31:25.216+00'),
    ('02014010', '2026-02-09 22:39:17.820904+00', '2026-02-09 22:39:15.901+00'),
    ('06210020', '2026-02-09 22:39:41.700997+00', '2026-02-09 22:39:39.831+00'),
    ('06441030', '2026-02-09 22:39:56.120377+00', '2026-02-09 22:39:54.273+00'),
    ('06686060', '2026-02-09 22:40:28.184044+00', '2026-02-09 22:40:26.351+00'),
    ('86049110', '2026-02-09 22:40:47.126011+00', '2026-02-09 22:40:45.293+00'),
    ('06728040', '2026-02-09 22:40:55.692797+00', '2026-02-09 22:40:53.851+00'),
    ('06714040', '2026-03-13 14:17:49.646917+00', '2026-03-13 14:17:51.731+00'),
    ('06665040', '2026-04-28 18:48:17.100118+00', '2026-04-28 18:48:17.609+00'),
    ('14014010', '2026-05-04 18:35:20.628119+00', '2026-05-04 18:35:21.874+00'),
    ('06882050', '2026-05-12 21:26:58.267011+00', '2026-05-12 21:26:58.035+00'),
    ('06714010', '2026-06-19 15:00:10.801892+00', '2026-06-19 15:00:14.24+00')
) AS v (indec_id, created_at, updated_at)
WHERE g.indec_id = v.indec_id
  AND g.updated_at_utc = g.created_at_utc
  AND g.created_at_utc > v.created_at::timestamptz
  AND EXISTS (SELECT 1 FROM _vv_seed_ctx);

-- Number format: Vaca Verde writes kilos with a decimal dot ("1.5"). Only while the setting was never
-- changed from the app (still the Comma default and no audited settings update), so a later manual choice stays.
UPDATE organizations o
SET quantity_decimal_separator = 'Dot'
FROM _vv_seed_ctx c
WHERE o.id = c.organization_id
  AND o.quantity_decimal_separator = 'Comma'
  AND NOT EXISTS (SELECT 1 FROM audit_log a
                  WHERE a.organization_id = o.id AND a.action = 'organization.settings_updated');

-- Business types.
INSERT INTO business_types (id, organization_id, name, key, sort_order)
SELECT md5('vaca-verde:business-type:' || v.key)::uuid, c.organization_id, v.name, v.key, v.sort_order::integer
FROM (VALUES
    ('Almacén', 'almacen', '1'),
    ('Bodegón', 'bodegon', '2'),
    ('Carnicería', 'carniceria', '3'),
    ('Carrito', 'carrito', '4'),
    ('Estación de Servicio', 'estacion_de_servicio', '5'),
    ('Parrilla', 'parrilla', '6'),
    ('Pollería', 'polleria', '7'),
    ('Resto Bar', 'resto_bar', '8'),
    ('Rotisería', 'rotiseria', '9'),
    ('Sanguchería', 'sangucheria', '10'),
    ('Supermercado', 'supermercado', '11')
) AS v (name, key, sort_order)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;

-- Customers (Wholesale, enabled). The id derives from `key` (name + city slug).
INSERT INTO customers (id, organization_id, customer_kind, display_name, address_street, phone,
                       city_id, business_type_id, tax_id_type, tax_id, notes, is_enabled, created_by_user_id)
SELECT md5('vaca-verde:customer:' || v.key)::uuid, c.organization_id, 'Wholesale', v.display_name,
       v.address_street, v.phone, ci.id, bt.id, v.tax_id_type, v.tax_id, v.notes, true, c.user_id
FROM (VALUES
    ('adan-rito-pontaquarto', 'Adan Rito Pontaquarto', NULL, NULL, NULL, NULL, 'Cuit', '20338138874', NULL),
    ('al-toque--capitan_sarmiento', 'Al Toque', NULL, '2478476538', '06140010', 'rotiseria', 'None', NULL, 'También: Parrilla'),
    ('almacen-cristian--arrecifes', 'Almacén Cristian', 'Av. Cordoba', '2478466104', '06077010', 'almacen', 'None', NULL, NULL),
    ('almacen-esteban--arrecifes', 'Almacén Esteban', 'Brasil 1132', '2478408929', '06077010', 'almacen', 'None', NULL, NULL),
    ('almacen-ferreti--arrecifes', 'Almacén Ferreti', 'F Cancha Hurac', '2478502607', '06077010', 'almacen', 'None', NULL, NULL),
    ('almacen-karina--arrecifes', 'Almacén Karina', 'Av. Belgrano', '2478518580', '06077010', 'almacen', 'None', NULL, 'También: Pollería'),
    ('antonella-ulujan-rolandi', 'Antonella Uluján Rolandi', NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('ariel-padre--san_nicolas', 'Ariel Padre', 'Avenida ?', '3364612756', '06763050', NULL, 'None', NULL, NULL),
    ('autoservicio-arrecifes--arrecifes', 'Autoservicio Arrecifes', 'Palermo R. Rojas', '2478520672', '06077010', 'supermercado', 'None', NULL, NULL),
    ('balthazar--san_antonio_de_areco', 'Balthazar', NULL, '1154190141', '06735020', 'resto_bar', 'None', NULL, NULL),
    ('bambini--arrecifes', 'Bambini', NULL, '1130099695', '06077010', 'resto_bar', 'None', NULL, NULL),
    ('bar-plaza--arrecifes', 'Bar Plaza', 'Rivadavia y R Gutier', '2478462532', '06077010', 'resto_bar', 'None', NULL, NULL),
    ('baratini--capitan_sarmiento', 'Baratini', NULL, NULL, '06140010', 'carniceria', 'None', NULL, 'Especificación original: CARNIC "LA MARCA"'),
    ('belen-club-river--arrecifes', 'Belen Club River', NULL, '2478466174', '06077010', 'almacen', 'None', NULL, NULL),
    ('berges--capitan_sarmiento', 'Berges', NULL, NULL, '06140010', NULL, 'None', NULL, NULL),
    ('bodegon--capitan_sarmiento', 'Bodegón', NULL, NULL, '06140010', 'resto_bar', 'None', NULL, 'También: Bodegón'),
    ('cantabria--arrecifes', 'Cantabria', 'Av. Merlassino', '2478520758', '06077010', 'resto_bar', 'None', NULL, NULL),
    ('carlos-dario-sabino', 'Carlos Darío Sabino', NULL, NULL, NULL, NULL, 'Cuit', '20173783648', NULL),
    ('carniceria--capitan_sarmiento', 'Carnicería', NULL, NULL, '06140010', 'carniceria', 'None', NULL, NULL),
    ('carniceria-baez--san_antonio_de_areco', 'Carnicería Baez', NULL, '3329525117', '06735020', 'carniceria', 'None', NULL, NULL),
    ('carrito-alta-pinta--arrecifes', 'Carrito Alta Pinta', NULL, '2478410391', '06077010', 'carrito', 'None', NULL, NULL),
    ('carrito-cacho--arrecifes', 'Carrito Cacho', NULL, '2478477034', '06077010', 'carrito', 'None', NULL, NULL),
    ('carrito-don-lolo--arrecifes', 'Carrito Don Lolo', NULL, '2478502520', '06077010', 'carrito', 'None', NULL, NULL),
    ('carrito-franco-rios--arrecifes', 'Carrito Franco Rios', NULL, '2478466029', '06077010', 'carrito', 'None', NULL, NULL),
    ('chuanyan-he', 'Chuanyan He', NULL, NULL, NULL, NULL, 'Cuit', '20940518548', NULL),
    ('cliente-coti--capitan_sarmiento', 'Cliente Coti', NULL, NULL, '06140010', 'carniceria', 'None', NULL, NULL),
    ('coti--salto', 'Coti', 'Arredondo 167', '2474683008', '06714060', NULL, 'None', NULL, NULL),
    ('crisol--arrecifes', 'Crisol', NULL, '2478542341', '06077010', 'parrilla', 'None', NULL, NULL),
    ('damian-parrilla--capitan_sarmiento', 'Damian Parrilla', NULL, '2478496220', '06140010', 'parrilla', 'None', NULL, NULL),
    ('derlis-tomas-riva', 'Derlis Tomás Riva', NULL, NULL, NULL, 'carniceria', 'None', NULL, NULL),
    ('despensa-tiki-tiki--arrecifes', 'Despensa Tiki Tiki', NULL, '2478469397', '06077010', 'almacen', 'None', NULL, NULL),
    ('diego-ortiz--capitan_sarmiento', 'Diego Ortiz', NULL, '2478514837', '06140010', NULL, 'None', NULL, NULL),
    ('eduardo-karina--arrecifes', 'Eduardo (Karina)', NULL, '2478509566', '06077010', 'almacen', 'None', NULL, NULL),
    ('el-condor--san_pedro', 'El Condor', NULL, '3329696757', '06770050', 'carniceria', 'None', NULL, NULL),
    ('el-guti--arrecifes', 'El Guti', 'R. Gutierrez', '2478402431', '06077010', 'resto_bar', 'None', NULL, NULL),
    ('el-mono--arrecifes', 'El Mono', 'Alberdi', '2478543711', '06077010', 'almacen', 'None', NULL, NULL),
    ('el-tata--capitan_sarmiento', 'El Tata', NULL, '2325689453', '06140010', 'parrilla', 'None', NULL, NULL),
    ('entre-panes--arrecifes', 'Entre Panes', NULL, '2478465824', '06077010', 'sangucheria', 'None', NULL, NULL),
    ('facundo-d-valle--arrecifes', 'Facundo D Valle', NULL, '2478460750', '06077010', 'polleria', 'None', NULL, NULL),
    ('herrera-mauricio-eugenio', 'Herrera Mauricio Eugenio', NULL, NULL, NULL, NULL, 'Cuit', '20315384088', NULL),
    ('javier--baradero', 'Javier', 'Ruta 9', NULL, '06070010', NULL, 'None', NULL, NULL),
    ('javier-salvador-kapp', 'Javier Salvador Kapp', NULL, NULL, NULL, 'carniceria', 'Cuit', '20284364156', NULL),
    ('jormer--arrecifes', 'Jormer', 'S H Perez y P Sard', '2478507746', '06077010', NULL, 'None', NULL, NULL),
    ('jose-maria-bogarin--san_antonio_de_areco', 'José María Bogarín', NULL, NULL, '06735020', 'carniceria', 'Cuit', '20275555739', NULL),
    ('jose-maria-esperanza', 'José María Esperanza', NULL, NULL, NULL, 'carniceria', 'Dni', '27015956', NULL),
    ('juan-domingo-figueroa--salto', 'Juan Domingo Figueroa', NULL, NULL, '06714060', 'carniceria', 'Cuit', '20241371825', NULL),
    ('juan-porcel--arrecifes', 'Juan Porcel', NULL, '2478403624', '06077010', 'carniceria', 'None', NULL, NULL),
    ('karen-lucia-leguizamon', 'Karen Lucia Leguizamon', NULL, NULL, NULL, NULL, 'Dni', '40998413', NULL),
    ('la-cuadra--capitan_sarmiento', 'La Cuadra', NULL, '2478441520', '06140010', 'resto_bar', 'None', NULL, NULL),
    ('la-picasa--baradero', 'La Picasa', NULL, '3329691185', '06070010', 'parrilla', 'None', NULL, NULL),
    ('la-rosita--san_antonio_de_areco', 'La Rosita', NULL, '1140444036', '06735020', NULL, 'None', NULL, NULL),
    ('la-sapiola--san_antonio_de_areco', 'La Sapiola', NULL, '2304553227', '06735020', 'resto_bar', 'None', NULL, NULL),
    ('las-amalias--san_pedro', 'Las Amalias', NULL, '3329626661', '06770050', 'parrilla', 'None', NULL, NULL),
    ('lo-de-rueda--arrecifes', 'Lo de Rueda', NULL, '3407415701', '06077010', 'resto_bar', 'None', NULL, 'También: Parrilla'),
    ('locos-de-asar--arrecifes', 'Locos de Asar', 'Av. R. Saenz P.', '2478506450', '06077010', 'parrilla', 'None', NULL, NULL),
    ('los-abraham--san_pedro', 'Los Abraham', NULL, '3329625588', '06770050', 'parrilla', 'None', NULL, NULL),
    ('los-abraham-luis--rio_tala', 'Los Abraham Luis', NULL, NULL, '06770040', NULL, 'None', NULL, NULL),
    ('luis-figueroa--salto', 'Luis Figueroa', NULL, NULL, '06714060', 'carniceria', 'None', NULL, NULL),
    ('luis-gallo--capitan_sarmiento', 'Luis Gallo', NULL, '2478420011', '06140010', NULL, 'None', NULL, NULL),
    ('machello-luciano-noel--chacabuco', 'Machello Luciano Noel', 'Buenos Aires y Zapiola', NULL, '06210020', 'carniceria', 'Cuit', '20276231961', NULL),
    ('maria-vanesa-diaz', 'María Vanesa Díaz', NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('mario-alvarez--capitan_sarmiento', 'Mario Alvarez', NULL, NULL, '06140010', 'carniceria', 'None', NULL, NULL),
    ('martin-super-jardin--pergamino', 'Martin Super Jardin', 'Av. Principal', '2477316656', '06623100', 'supermercado', 'None', NULL, NULL),
    ('martinez-santiago--salto', 'Martínez Santiago', 'San Pablo y Bolívar', NULL, '06714060', NULL, 'Cuit', '23327154699', NULL),
    ('mingo-alfaro--arrecifes', 'Mingo Alfaro', 'Urquiza', NULL, '06077010', 'polleria', 'None', NULL, NULL),
    ('miunoz-pipi--arrecifes', 'Miuñoz-Pipi', NULL, '2478409233', '06077010', 'almacen', 'None', NULL, 'También: Carrito'),
    ('nestor-bilbao--arrecifes', 'Nestor Bilbao', 'Palermo', '2478461601', '06077010', 'carniceria', 'None', NULL, 'También: Almacén'),
    ('nicolas-eduardo-pagano', 'Nicolás Eduardo Pagano', NULL, NULL, NULL, NULL, 'Cuit', '20314134681', NULL),
    ('palmieri-federico-hernan', 'Palmieri Federico Hernán', NULL, NULL, NULL, NULL, 'Dni', '25137726', NULL),
    ('parrilla-avanti--san_antonio_de_areco', 'Parrilla Avanti', NULL, '2325519316', '06735020', 'parrilla', 'None', NULL, NULL),
    ('parrilla-caio--pergamino', 'Parrilla Caio', 'Ruta', '2477453141', '06623100', 'parrilla', 'None', NULL, NULL),
    ('parrilla-don-manuel--san_antonio_de_areco', 'Parrilla Don Manuel', 'Ruta 8 (Vieja)', '2326403064', '06735020', 'parrilla', 'None', NULL, NULL),
    ('parrilla-javier--baradero', 'Parrilla Javier', 'Ruta 9', '3329627731', '06070010', 'parrilla', 'None', NULL, NULL),
    ('parrilla-los-pinos--capitan_sarmiento', 'Parrilla Los Pinos', NULL, '2478556809', '06140010', 'parrilla', 'None', NULL, NULL),
    ('patricia-biela--arrecifes', 'Patricia Biela', 'Ruta 8 y 51', '2478556572', '06077010', NULL, 'None', NULL, NULL),
    ('peralta-oscar--capitan_sarmiento', 'Peralta Oscar', 'Av. Alem y Corrientes', '2478463463', '06140010', NULL, 'None', NULL, NULL),
    ('pillado-joaquin', 'Pillado Joaquín', NULL, NULL, NULL, NULL, 'None', NULL, NULL),
    ('pyp--arrecifes', 'PyP', NULL, '2478409302', '06077010', 'rotiseria', 'None', NULL, NULL),
    ('ramiro-paz', 'Ramiro Paz', NULL, NULL, NULL, NULL, 'Cuit', '20334104169', NULL),
    ('rene-alberto-caviglia', 'René Alberto Caviglia', NULL, NULL, NULL, NULL, 'Cuit', '20106630578', NULL),
    ('segundo-valloire--salto', 'Segundo Valloire', NULL, NULL, '06714060', 'carniceria', 'Dni', '30308717', NULL),
    ('serafina-david--arrecifes', 'Serafina David', 'España y Moreno', '2478466796', '06077010', NULL, 'None', NULL, NULL),
    ('shell-sarmiento--capitan_sarmiento', 'Shell Sarmiento', NULL, '1136303440', '06140010', 'estacion_de_servicio', 'None', NULL, NULL),
    ('super-baez--san_antonio_de_areco', 'Super Baez', NULL, '3487707061', '06735020', 'supermercado', 'None', NULL, NULL),
    ('turco-guillermo--arrecifes', 'Turco Guillermo', 'Fonavi', NULL, '06077010', NULL, 'None', NULL, NULL),
    ('valeria-resto--arrecifes', 'Valeria Resto', 'Av. Sarmiento', '2478503181', '06077010', 'resto_bar', 'None', NULL, NULL),
    ('willie-carniceria--capitan_sarmiento', 'Willie Carnicería', '(Fonavi/El Campeon)', '3415785507', '06140010', 'carniceria', 'None', NULL, 'Especificación original: Súper Campeones')
) AS v (key, display_name, address_street, phone, city_indec_id, business_type_key, tax_id_type, tax_id, notes)
CROSS JOIN _vv_seed_ctx c
LEFT JOIN cities ci ON ci.indec_id = v.city_indec_id
LEFT JOIN business_types bt ON bt.organization_id = c.organization_id AND bt.key = v.business_type_key
ON CONFLICT DO NOTHING;

-- Contacts: the CLIENTE column as each customer's primary contact (id derives from the customer key).
INSERT INTO customer_contacts (id, organization_id, customer_id, first_name, last_name, is_primary)
SELECT md5('vaca-verde:contact:' || v.key)::uuid, c.organization_id, md5('vaca-verde:customer:' || v.key)::uuid,
       v.first_name, v.last_name, true
FROM (VALUES
    ('al-toque--capitan_sarmiento', 'Lucas Badano', NULL),
    ('almacen-esteban--arrecifes', 'Esteban', NULL),
    ('almacen-karina--arrecifes', 'Karina', NULL),
    ('balthazar--san_antonio_de_areco', 'Martin', NULL),
    ('bambini--arrecifes', 'Laura', NULL),
    ('bar-plaza--arrecifes', 'Celeste', NULL),
    ('belen-club-river--arrecifes', 'Belen', NULL),
    ('berges--capitan_sarmiento', 'Bernardo', NULL),
    ('bodegon--capitan_sarmiento', 'Gaston', NULL),
    ('cantabria--arrecifes', 'Ani', NULL),
    ('carniceria--capitan_sarmiento', 'Joaquin', NULL),
    ('carniceria-baez--san_antonio_de_areco', 'Ignacio', NULL),
    ('crisol--arrecifes', 'Tola', NULL),
    ('damian-parrilla--capitan_sarmiento', 'Damian', NULL),
    ('diego-ortiz--capitan_sarmiento', 'Diego', NULL),
    ('eduardo-karina--arrecifes', 'Eduardo', NULL),
    ('el-condor--san_pedro', 'Felipe', NULL),
    ('el-guti--arrecifes', 'Mirko', NULL),
    ('el-mono--arrecifes', 'Carlitos', NULL),
    ('el-tata--capitan_sarmiento', 'Iris', NULL),
    ('entre-panes--arrecifes', 'Gonza', NULL),
    ('facundo-d-valle--arrecifes', 'Facu', NULL),
    ('juan-porcel--arrecifes', 'Juan', NULL),
    ('la-picasa--baradero', 'Javier', NULL),
    ('la-sapiola--san_antonio_de_areco', 'Hernan', NULL),
    ('las-amalias--san_pedro', 'Walter', NULL),
    ('lo-de-rueda--arrecifes', 'Martin', NULL),
    ('locos-de-asar--arrecifes', 'Tito', NULL),
    ('los-abraham--san_pedro', 'Luis', NULL),
    ('mingo-alfaro--arrecifes', 'Mingo', NULL),
    ('miunoz-pipi--arrecifes', 'Walter', NULL),
    ('nestor-bilbao--arrecifes', 'Nestor', NULL),
    ('parrilla-avanti--san_antonio_de_areco', 'Remigio', NULL),
    ('parrilla-javier--baradero', 'Javier Bargas', NULL),
    ('parrilla-los-pinos--capitan_sarmiento', 'Natalia', NULL),
    ('pyp--arrecifes', 'Pelusa', NULL),
    ('shell-sarmiento--capitan_sarmiento', 'Sebastian', NULL),
    ('super-baez--san_antonio_de_areco', 'Juan Ignacio', NULL),
    ('valeria-resto--arrecifes', 'Carlitos', NULL)
) AS v (key, first_name, last_name)
CROSS JOIN _vv_seed_ctx c
WHERE EXISTS (SELECT 1 FROM customers cu
              WHERE cu.organization_id = c.organization_id AND cu.id = md5('vaca-verde:customer:' || v.key)::uuid)
ON CONFLICT DO NOTHING;


COMMIT;
