-- Vaca Verde suppliers seed: the supplier category "Carne", the suppliers and their contacts.
--
-- GENERATED by generate_suppliers_catalog.py from the owner's spreadsheets - do not
-- edit by hand; see README.md in this directory.
-- Cities are global Georef data (migration 0028); suppliers point at them by INDEC id.
--
-- Safe to re-run: every row has a deterministic id (md5('vaca-verde:<kind>:<key>')::uuid)
-- and is inserted with ON CONFLICT DO NOTHING, so a second run changes nothing and never
-- overwrites later edits. When the organization "Vaca Verde" (or its business admin) does not
-- exist yet, the file prints a NOTICE and changes nothing. Apply after 001 (and migrations 0030 / 0016-0018).
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 002_vaca_verde_suppliers.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the records.';
        RETURN;
    END IF;

    INSERT INTO _vv_seed_ctx (organization_id, user_id) VALUES (v_org, v_user);
END $$;

-- Supplier category "Carne" (organization scoped; found by key when it already exists).
INSERT INTO supplier_categories (id, organization_id, name, key, sort_order)
SELECT md5('vaca-verde:supplier-category:carne')::uuid, c.organization_id, 'Carne', 'carne', 0
FROM _vv_seed_ctx c
ON CONFLICT DO NOTHING;

-- Suppliers. The id derives from the name slug; the category is looked up by key.
INSERT INTO suppliers (id, organization_id, display_name, phone, email, address_street, address_number,
                       city_id, category_id, is_enabled, created_by_user_id)
SELECT md5('vaca-verde:supplier:' || v.key)::uuid, c.organization_id, v.display_name, v.phone, v.email,
       v.address_street, v.address_number, ci.id, sc.id, true, c.user_id
FROM (VALUES
    ('swift', 'Swift', '3416254888', 'nelson.beber@minervafoods.com', NULL, NULL, '82084270'),
    ('urien-loza', 'Urien Loza', '1153021969', NULL, NULL, NULL, '06638040'),
    ('ventas-df-distribuidora', 'Ventas DF Distribuidora', '1139493069', NULL, NULL, NULL, '0686101005'),
    ('carniceria-cow', 'Carnicería Cow', '1160223630', NULL, 'Av. Nazca', '5096', '02014010'),
    ('frigorifico-merlo', 'Frigorífico Merlo', '2204995149', 'info@frigorificomerlo.com', 'Elías Alippi', '1890', '06539010'),
    ('frigorifico-gorina', 'Frigorífico Gorina', '1139844090', NULL, NULL, NULL, NULL),
    ('frigorifico-frigolar', 'Frigorífico Frigolar', '2216550132', NULL, NULL, NULL, NULL),
    ('amalia', 'Amalia', '3329544332', NULL, NULL, NULL, '06770050'),
    ('frimsa', 'Frimsa', NULL, NULL, NULL, NULL, NULL)
) AS v (key, display_name, phone, email, address_street, address_number, city_indec_id)
CROSS JOIN _vv_seed_ctx c
LEFT JOIN cities ci ON ci.indec_id = v.city_indec_id
LEFT JOIN supplier_categories sc ON sc.organization_id = c.organization_id AND sc.key = 'carne'
ON CONFLICT DO NOTHING;

-- Contacts: the first one of each supplier is its primary contact.
INSERT INTO supplier_contacts (id, organization_id, supplier_id, first_name, last_name, phone, email, role,
                              is_primary, sort_order)
SELECT md5('vaca-verde:supplier-contact:' || v.key || ':' || v.n)::uuid, c.organization_id,
       md5('vaca-verde:supplier:' || v.key)::uuid, v.first_name, v.last_name, v.phone, v.email, v.role,
       v.is_primary, v.n::integer
FROM (VALUES
    ('swift', '0', 'Nelson Luis Beber Valdemarin', NULL, NULL, 'nelson.beber@minervafoods.com', NULL, true::boolean),
    ('urien-loza', '0', 'Marcos', 'Loza', NULL, NULL, NULL, true::boolean),
    ('ventas-df-distribuidora', '0', 'Gustavo', NULL, NULL, NULL, 'Depósito', true::boolean),
    ('frigorifico-merlo', '0', 'Eduardo', 'Manchessot', NULL, NULL, NULL, true::boolean),
    ('frigorifico-gorina', '0', 'Lautaro', 'Silvestri', NULL, NULL, NULL, true::boolean),
    ('frigorifico-frigolar', '0', 'Carlos', 'Charton', NULL, NULL, NULL, true::boolean),
    ('frimsa', '0', 'Agustín', 'Villarino', '1160521221', NULL, NULL, true::boolean),
    ('frimsa', '1', 'Matías', 'Villarino', '1163701224', NULL, NULL, false::boolean)
) AS v (key, n, first_name, last_name, phone, email, role, is_primary)
CROSS JOIN _vv_seed_ctx c
WHERE EXISTS (SELECT 1 FROM suppliers s
              WHERE s.organization_id = c.organization_id AND s.id = md5('vaca-verde:supplier:' || v.key)::uuid)
ON CONFLICT DO NOTHING;


COMMIT;
