-- Vaca Verde catalog seed: product categories, products, presentations and price lists.
--
-- GENERATED by generate_suppliers_catalog.py from the owner's spreadsheets - do not
-- edit by hand; see README.md in this directory.
-- Branch "Ruta 51" hosts the butcher shop and the distribution: one catalog, two price lists
-- (Mostrador = default, final prices here and base prices from 004; Reparto = base + list-specific rate components).
-- Product codes 001... are provisional (scale integration will replace them).
--
-- Safe to re-run: every row has a deterministic id (md5('vaca-verde:<kind>:<key>')::uuid)
-- and is inserted with ON CONFLICT DO NOTHING, so a second run changes nothing and never
-- overwrites later edits. When the organization "Vaca Verde" (or its business admin, or its branch "Ruta 51") does not
-- exist yet, the file prints a NOTICE and changes nothing. Apply after 001 (and migrations 0030 / 0016-0018).
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 003_vaca_verde_catalog.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL, branch_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
    v_branch uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the records.';
        RETURN;
    END IF;

    SELECT id INTO v_branch
    FROM branches
    WHERE organization_id = v_org AND lower(btrim(name)) = 'ruta 51'
    ORDER BY created_at, id
    LIMIT 1;

    IF v_branch IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no branch named "Ruta 51" to own the catalog.';
        RETURN;
    END IF;

    -- Branch-owned tables (catalog and pricing) are keyed on this setting too; transaction-local.
    PERFORM set_config('app.current_branch_id', v_branch::text, true);

    INSERT INTO _vv_seed_ctx (organization_id, user_id, branch_id) VALUES (v_org, v_user, v_branch);
END $$;

-- Product categories (found by name when they already exist). Almacén and Bebidas start empty.
INSERT INTO categories (id, organization_id, name, icon_key)
SELECT md5('vaca-verde:category:' || v.key)::uuid, c.organization_id, v.name, v.icon_key
FROM (VALUES
    ('Vacuno', 'vacuno', 'meat'),
    ('Cerdo', 'cerdo', 'meat'),
    ('Embutidos', 'embutidos', 'meat'),
    ('Pollo', 'pollo', 'poultry'),
    ('Achuras', 'achuras', 'meat'),
    ('Milanesas', 'milanesas', 'meat'),
    ('Almacén', 'almacen', 'grocery'),
    ('Bebidas', 'bebidas', 'drinks')
) AS v (name, key, icon_key)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;

-- Products. The category is resolved by name; the unit is a bare uuid (no units table exists yet):
-- md5('vaca-verde:unit:kg') stands for kilograms.
INSERT INTO products (id, organization_id, branch_id, name, category_id, default_unit_id, created_by_user_id)
SELECT md5('vaca-verde:product:' || v.key)::uuid, c.organization_id, c.branch_id, v.name, cat.id,
       md5('vaca-verde:unit:kg')::uuid, c.user_id
FROM (VALUES
    ('aguja', 'Aguja', 'Vacuno'),
    ('aguja-especial', 'Aguja especial', 'Vacuno'),
    ('asado-completo', 'Asado completo', 'Vacuno'),
    ('asado-rueda', 'Asado rueda', 'Vacuno'),
    ('bife-de-chorizo', 'Bife de chorizo', 'Vacuno'),
    ('bola-de-lomo', 'Bola de lomo', 'Vacuno'),
    ('bola-de-lomo-feteada', 'Bola de lomo feteada', 'Vacuno'),
    ('cima', 'Cima', 'Vacuno'),
    ('colita-de-cuadril', 'Colita de cuadril', 'Vacuno'),
    ('corazon-de-cuadril', 'Corazón de cuadril', 'Vacuno'),
    ('corte-americano', 'Corte americano', 'Vacuno'),
    ('costeleta', 'Costeleta', 'Vacuno'),
    ('costilla', 'Costilla', 'Vacuno'),
    ('cuadrada', 'Cuadrada', 'Vacuno'),
    ('cuadrada-feteada', 'Cuadrada feteada', 'Vacuno'),
    ('cuadril', 'Cuadril', 'Vacuno'),
    ('entrana', 'Entraña', 'Vacuno'),
    ('entrana-vaca-congelada', 'Entraña vaca congelada', 'Vacuno'),
    ('falda', 'Falda', 'Vacuno'),
    ('lomo', 'Lomo', 'Vacuno'),
    ('matambre', 'Matambre', 'Vacuno'),
    ('nalga', 'Nalga', 'Vacuno'),
    ('nalga-con-tapa', 'Nalga con tapa', 'Vacuno'),
    ('nalga-feteada', 'Nalga feteada', 'Vacuno'),
    ('nalga-sin-tapa', 'Nalga sin tapa', 'Vacuno'),
    ('osobuco', 'Osobuco', 'Vacuno'),
    ('paleta', 'Paleta', 'Vacuno'),
    ('palomita', 'Palomita', 'Vacuno'),
    ('peceto', 'Peceto', 'Vacuno'),
    ('pecho', 'Pecho', 'Vacuno'),
    ('picada', 'Picada', 'Vacuno'),
    ('roast-beef', 'Roast beef', 'Vacuno'),
    ('rueda', 'Rueda', 'Vacuno'),
    ('sin-ral', 'Sin ral', 'Vacuno'),
    ('tapa-de-asado', 'Tapa de asado', 'Vacuno'),
    ('tapa-de-nalga', 'Tapa de nalga', 'Vacuno'),
    ('vacio', 'Vacío', 'Vacuno'),
    ('vacio-marca-santa-ines', 'Vacío marca Santa Inés', 'Vacuno'),
    ('vacio-novillo-seleccionado', 'Vacío novillo seleccionado', 'Vacuno'),
    ('bola-de-lomo-de-cerdo', 'Bola de lomo de cerdo', 'Cerdo'),
    ('bondiola', 'Bondiola', 'Cerdo'),
    ('costilla-de-cerdo', 'Costilla de cerdo', 'Cerdo'),
    ('cuadrada-de-cerdo', 'Cuadrada de cerdo', 'Cerdo'),
    ('cuadril-de-cerdo', 'Cuadril de cerdo', 'Cerdo'),
    ('lomo-de-cerdo', 'Lomo de cerdo', 'Cerdo'),
    ('matambre-de-cerdo', 'Matambre de cerdo', 'Cerdo'),
    ('nalga-de-cerdo', 'Nalga de cerdo', 'Cerdo'),
    ('papada', 'Papada', 'Cerdo'),
    ('pechito', 'Pechito', 'Cerdo'),
    ('pernil', 'Pernil', 'Cerdo'),
    ('picada-de-cerdo', 'Picada de cerdo', 'Cerdo'),
    ('pulpa', 'Pulpa', 'Cerdo'),
    ('solomillo', 'Solomillo', 'Cerdo'),
    ('tortuguita', 'Tortuguita', 'Cerdo'),
    ('bondiola-salada', 'Bondiola salada', 'Embutidos'),
    ('chorizo-colorado', 'Chorizo colorado', 'Embutidos'),
    ('chorizo-fresco', 'Chorizo fresco', 'Embutidos'),
    ('chorizo-seco', 'Chorizo seco', 'Embutidos'),
    ('jamon-crudo', 'Jamón crudo', 'Embutidos'),
    ('morcilla', 'Morcilla', 'Embutidos'),
    ('salame', 'Salame', 'Embutidos'),
    ('salamin-picado-fino', 'Salamín picado fino', 'Embutidos'),
    ('salamin-picado-grueso', 'Salamín picado grueso', 'Embutidos'),
    ('salchicha-parrillera', 'Salchicha parrillera', 'Embutidos'),
    ('alitas', 'Alitas', 'Pollo'),
    ('carcaza', 'Carcaza', 'Pollo'),
    ('menudos', 'Menudos', 'Pollo'),
    ('pata', 'Pata', 'Pollo'),
    ('pata-y-muslo', 'Pata y muslo', 'Pollo'),
    ('patitas', 'Patitas', 'Pollo'),
    ('pechuga', 'Pechuga', 'Pollo'),
    ('pollo-entero', 'Pollo entero', 'Pollo'),
    ('trozado', 'Trozado', 'Pollo'),
    ('centro', 'Centro', 'Achuras'),
    ('chinchulin', 'Chinchulín', 'Achuras'),
    ('corazon', 'Corazón', 'Achuras'),
    ('cuajada', 'Cuajada', 'Achuras'),
    ('higado', 'Hígado', 'Achuras'),
    ('lengua', 'Lengua', 'Achuras'),
    ('molleja', 'Molleja', 'Achuras'),
    ('mondongo', 'Mondongo', 'Achuras'),
    ('rabo', 'Rabo', 'Achuras'),
    ('rinon', 'Riñón', 'Achuras'),
    ('sesos', 'Sesos', 'Achuras'),
    ('tripa-gorda', 'Tripa gorda', 'Achuras'),
    ('medallon-de-pollo', 'Medallón de pollo', 'Milanesas'),
    ('medallon-de-pollo-jamon-y-queso', 'Medallón de pollo jamón y queso', 'Milanesas'),
    ('milanesa-de-ternera-de-bola-de-lomo', 'Milanesa de ternera de bola de lomo', 'Milanesas'),
    ('milanesas-de-muslo', 'Milanesas de muslo', 'Milanesas'),
    ('milanesas-de-pechuga', 'Milanesas de pechuga', 'Milanesas')
) AS v (key, name, category_name)
CROSS JOIN _vv_seed_ctx c
JOIN categories cat ON cat.organization_id = c.organization_id AND lower(btrim(cat.name)) = lower(v.category_name)
ON CONFLICT DO NOTHING;

-- One Weighted presentation "Por kg" per product, code 001... ordered by category, then name.
INSERT INTO presentations (id, organization_id, branch_id, product_id, name, quantity_behavior, unit_id,
                           identification_code, created_by_user_id)
SELECT md5('vaca-verde:presentation:' || v.key)::uuid, c.organization_id, c.branch_id,
       md5('vaca-verde:product:' || v.key)::uuid, 'Por kg', 'Weighted', md5('vaca-verde:unit:kg')::uuid,
       v.code, c.user_id
FROM (VALUES
    ('aguja', '001'),
    ('aguja-especial', '002'),
    ('asado-completo', '003'),
    ('asado-rueda', '004'),
    ('bife-de-chorizo', '005'),
    ('bola-de-lomo', '006'),
    ('bola-de-lomo-feteada', '007'),
    ('cima', '008'),
    ('colita-de-cuadril', '009'),
    ('corazon-de-cuadril', '010'),
    ('corte-americano', '011'),
    ('costeleta', '012'),
    ('costilla', '013'),
    ('cuadrada', '014'),
    ('cuadrada-feteada', '015'),
    ('cuadril', '016'),
    ('entrana', '017'),
    ('entrana-vaca-congelada', '018'),
    ('falda', '019'),
    ('lomo', '020'),
    ('matambre', '021'),
    ('nalga', '022'),
    ('nalga-con-tapa', '023'),
    ('nalga-feteada', '024'),
    ('nalga-sin-tapa', '025'),
    ('osobuco', '026'),
    ('paleta', '027'),
    ('palomita', '028'),
    ('peceto', '029'),
    ('pecho', '030'),
    ('picada', '031'),
    ('roast-beef', '032'),
    ('rueda', '033'),
    ('sin-ral', '034'),
    ('tapa-de-asado', '035'),
    ('tapa-de-nalga', '036'),
    ('vacio', '037'),
    ('vacio-marca-santa-ines', '038'),
    ('vacio-novillo-seleccionado', '039'),
    ('bola-de-lomo-de-cerdo', '040'),
    ('bondiola', '041'),
    ('costilla-de-cerdo', '042'),
    ('cuadrada-de-cerdo', '043'),
    ('cuadril-de-cerdo', '044'),
    ('lomo-de-cerdo', '045'),
    ('matambre-de-cerdo', '046'),
    ('nalga-de-cerdo', '047'),
    ('papada', '048'),
    ('pechito', '049'),
    ('pernil', '050'),
    ('picada-de-cerdo', '051'),
    ('pulpa', '052'),
    ('solomillo', '053'),
    ('tortuguita', '054'),
    ('bondiola-salada', '055'),
    ('chorizo-colorado', '056'),
    ('chorizo-fresco', '057'),
    ('chorizo-seco', '058'),
    ('jamon-crudo', '059'),
    ('morcilla', '060'),
    ('salame', '061'),
    ('salamin-picado-fino', '062'),
    ('salamin-picado-grueso', '063'),
    ('salchicha-parrillera', '064'),
    ('alitas', '065'),
    ('carcaza', '066'),
    ('menudos', '067'),
    ('pata', '068'),
    ('pata-y-muslo', '069'),
    ('patitas', '070'),
    ('pechuga', '071'),
    ('pollo-entero', '072'),
    ('trozado', '073'),
    ('centro', '074'),
    ('chinchulin', '075'),
    ('corazon', '076'),
    ('cuajada', '077'),
    ('higado', '078'),
    ('lengua', '079'),
    ('molleja', '080'),
    ('mondongo', '081'),
    ('rabo', '082'),
    ('rinon', '083'),
    ('sesos', '084'),
    ('tripa-gorda', '085'),
    ('medallon-de-pollo', '086'),
    ('medallon-de-pollo-jamon-y-queso', '087'),
    ('milanesa-de-ternera-de-bola-de-lomo', '088'),
    ('milanesas-de-muslo', '089'),
    ('milanesas-de-pechuga', '090')
) AS v (key, code)
CROSS JOIN _vv_seed_ctx c
WHERE EXISTS (SELECT 1 FROM products p
              WHERE p.organization_id = c.organization_id AND p.id = md5('vaca-verde:product:' || v.key)::uuid)
ON CONFLICT DO NOTHING;

-- Price lists of the branch, resolved into _vv_lists(key, id):
--   * an existing list with the same name (case-insensitive) is reused;
--   * the branch's untouched empty "Default" list (the one provisioning creates) becomes "Mostrador";
--   * otherwise the list is created. Mostrador is created as the default only when the branch has none
--     (price_lists_one_default_per_branch allows one); Reparto never is.
CREATE TEMP TABLE _vv_lists (key text PRIMARY KEY, id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    c  _vv_seed_ctx%ROWTYPE;
    k  text;
    n  text;
    v_id uuid;
BEGIN
    SELECT * INTO c FROM _vv_seed_ctx;
    IF NOT FOUND THEN
        RETURN;
    END IF;

    UPDATE price_lists pl
    SET name = 'Mostrador'
    WHERE pl.organization_id = c.organization_id AND pl.branch_id = c.branch_id
      AND pl.is_default AND pl.name = 'Default'
      AND NOT EXISTS (SELECT 1 FROM price_list_entries e WHERE e.price_list_id = pl.id)
      AND NOT EXISTS (SELECT 1 FROM rate_component_sets s WHERE s.price_list_id = pl.id)
      AND NOT EXISTS (SELECT 1 FROM price_lists o
                      WHERE o.organization_id = c.organization_id AND o.branch_id = c.branch_id
                        AND lower(btrim(o.name)) = 'mostrador');

    FOREACH k IN ARRAY ARRAY['mostrador', 'reparto'] LOOP
        n := initcap(k);
        SELECT pl.id INTO v_id
        FROM price_lists pl
        WHERE pl.organization_id = c.organization_id AND pl.branch_id = c.branch_id
          AND lower(btrim(pl.name)) = k
        ORDER BY pl.created_at_utc, pl.id
        LIMIT 1;

        IF v_id IS NULL THEN
            v_id := md5('vaca-verde:price-list:' || k)::uuid;
            INSERT INTO price_lists (id, organization_id, branch_id, name, is_default, created_by_user_id)
            VALUES (v_id, c.organization_id, c.branch_id, n,
                    k = 'mostrador' AND NOT EXISTS (SELECT 1 FROM price_lists d
                                                    WHERE d.organization_id = c.organization_id
                                                      AND d.branch_id = c.branch_id AND d.is_default),
                    c.user_id)
            ON CONFLICT DO NOTHING;
            IF k = 'mostrador' AND NOT EXISTS (SELECT 1 FROM price_lists d
                                               WHERE d.id = v_id AND d.is_default) THEN
                RAISE NOTICE 'Vaca Verde catalog: the branch already has a different default price list; Mostrador was created but is not the default.';
            END IF;
        END IF;
        INSERT INTO _vv_lists (key, id) VALUES (k, v_id);
    END LOOP;
END $$;

-- Entries (effective from 2026-10-01). Reparto holds the BASE price; its rate set composes it.
INSERT INTO price_list_entries (id, organization_id, branch_id, price_list_id, presentation_id, unit_price,
                                effective_from, source, created_by_user_id)
SELECT md5('vaca-verde:price-entry:' || v.list_key || ':' || v.product_key || ':2026-10-01')::uuid,
       c.organization_id, c.branch_id, l.id, md5('vaca-verde:presentation:' || v.product_key)::uuid,
       v.unit_price::numeric(12,2), DATE '2026-10-01', 'Manual', c.user_id
FROM (VALUES
    ('mostrador', 'aguja', '17000.00'),
    ('mostrador', 'aguja-especial', '18000.00'),
    ('mostrador', 'alitas', '5500.00'),
    ('mostrador', 'bife-de-chorizo', '25000.00'),
    ('mostrador', 'bola-de-lomo', '18000.00'),
    ('mostrador', 'bola-de-lomo-de-cerdo', '9000.00'),
    ('mostrador', 'bondiola', '10500.00'),
    ('mostrador', 'bondiola-salada', '31000.00'),
    ('mostrador', 'carcaza', '3500.00'),
    ('mostrador', 'chinchulin', '8000.00'),
    ('mostrador', 'chorizo-colorado', '23200.00'),
    ('mostrador', 'chorizo-fresco', '11500.00'),
    ('mostrador', 'chorizo-seco', '25100.00'),
    ('mostrador', 'cima', '18000.00'),
    ('mostrador', 'colita-de-cuadril', '23000.00'),
    ('mostrador', 'corazon', '7500.00'),
    ('mostrador', 'corte-americano', '25000.00'),
    ('mostrador', 'costeleta', '19000.00'),
    ('mostrador', 'costilla', '17800.00'),
    ('mostrador', 'costilla-de-cerdo', '9200.00'),
    ('mostrador', 'cuadrada', '21000.00'),
    ('mostrador', 'cuadrada-de-cerdo', '8000.00'),
    ('mostrador', 'cuadril', '22000.00'),
    ('mostrador', 'cuadril-de-cerdo', '9000.00'),
    ('mostrador', 'cuajada', '6000.00'),
    ('mostrador', 'entrana', '23500.00'),
    ('mostrador', 'entrana-vaca-congelada', '20300.00'),
    ('mostrador', 'falda', '17000.00'),
    ('mostrador', 'higado', '7500.00'),
    ('mostrador', 'jamon-crudo', '31500.00'),
    ('mostrador', 'lengua', '11570.00'),
    ('mostrador', 'lomo', '25000.00'),
    ('mostrador', 'lomo-de-cerdo', '9000.00'),
    ('mostrador', 'matambre', '18000.00'),
    ('mostrador', 'matambre-de-cerdo', '16000.00'),
    ('mostrador', 'medallon-de-pollo', '10700.00'),
    ('mostrador', 'medallon-de-pollo-jamon-y-queso', '12500.00'),
    ('mostrador', 'menudos', '2000.00'),
    ('mostrador', 'milanesas-de-muslo', '8000.00'),
    ('mostrador', 'milanesas-de-pechuga', '10500.00'),
    ('mostrador', 'molleja', '32000.00'),
    ('mostrador', 'mondongo', '12000.00'),
    ('mostrador', 'morcilla', '8100.00'),
    ('mostrador', 'nalga', '23000.00'),
    ('mostrador', 'nalga-de-cerdo', '8000.00'),
    ('mostrador', 'osobuco', '14000.00'),
    ('mostrador', 'paleta', '18000.00'),
    ('mostrador', 'palomita', '17000.00'),
    ('mostrador', 'papada', '9000.00'),
    ('mostrador', 'pata', '7300.00'),
    ('mostrador', 'pata-y-muslo', '6500.00'),
    ('mostrador', 'patitas', '10700.00'),
    ('mostrador', 'peceto', '23000.00'),
    ('mostrador', 'pechito', '7800.00'),
    ('mostrador', 'pechuga', '14000.00'),
    ('mostrador', 'pernil', '14000.00'),
    ('mostrador', 'picada', '15000.00'),
    ('mostrador', 'picada-de-cerdo', '10000.00'),
    ('mostrador', 'pollo-entero', '6000.00'),
    ('mostrador', 'pulpa', '8000.00'),
    ('mostrador', 'rabo', '10200.00'),
    ('mostrador', 'rinon', '7000.00'),
    ('mostrador', 'salame', '25500.00'),
    ('mostrador', 'salamin-picado-fino', '23200.00'),
    ('mostrador', 'salamin-picado-grueso', '23200.00'),
    ('mostrador', 'salchicha-parrillera', '13500.00'),
    ('mostrador', 'sesos', '5000.00'),
    ('mostrador', 'solomillo', '9000.00'),
    ('mostrador', 'tapa-de-asado', '20500.00'),
    ('mostrador', 'tapa-de-nalga', '23000.00'),
    ('mostrador', 'tortuguita', '8000.00'),
    ('mostrador', 'tripa-gorda', '8000.00'),
    ('mostrador', 'trozado', '5500.00'),
    ('mostrador', 'vacio', '21500.00'),
    ('reparto', 'asado-completo', '10600.00'),
    ('reparto', 'asado-rueda', '9000.00'),
    ('reparto', 'bola-de-lomo', '11400.00'),
    ('reparto', 'bola-de-lomo-feteada', '12900.00'),
    ('reparto', 'colita-de-cuadril', '15000.00'),
    ('reparto', 'corazon-de-cuadril', '13500.00'),
    ('reparto', 'cuadrada', '12000.00'),
    ('reparto', 'cuadrada-feteada', '13500.00'),
    ('reparto', 'entrana', '22500.00'),
    ('reparto', 'entrana-vaca-congelada', '14500.00'),
    ('reparto', 'matambre', '8000.00'),
    ('reparto', 'nalga-con-tapa', '12000.00'),
    ('reparto', 'nalga-feteada', '15000.00'),
    ('reparto', 'nalga-sin-tapa', '13500.00'),
    ('reparto', 'paleta', '11300.00'),
    ('reparto', 'peceto', '13500.00'),
    ('reparto', 'pecho', '7400.00'),
    ('reparto', 'roast-beef', '11300.00'),
    ('reparto', 'rueda', '8000.00'),
    ('reparto', 'sin-ral', '7900.00'),
    ('reparto', 'tapa-de-asado', '11300.00'),
    ('reparto', 'tapa-de-nalga', '10000.00'),
    ('reparto', 'vacio', '11000.00'),
    ('reparto', 'vacio-marca-santa-ines', '9500.00'),
    ('reparto', 'vacio-novillo-seleccionado', '12000.00')
) AS v (list_key, product_key, unit_price)
CROSS JOIN _vv_seed_ctx c
JOIN _vv_lists l ON l.key = v.list_key
WHERE EXISTS (SELECT 1 FROM presentations pr
              WHERE pr.organization_id = c.organization_id AND pr.branch_id = c.branch_id
                AND pr.id = md5('vaca-verde:presentation:' || v.product_key)::uuid)
ON CONFLICT DO NOTHING;

-- Reparto's rate components: LIST-SPECIFIC (price_list_id = Reparto, never the organization default),
-- so Mostrador is not composed by this seed (004 gives it its own set). All four apply to the base: base x 1.45.
INSERT INTO rate_component_sets (id, organization_id, branch_id, price_list_id, effective_from, created_by_user_id)
SELECT md5('vaca-verde:rate-set:reparto:2026-10-01')::uuid, c.organization_id, c.branch_id, l.id, DATE '2026-10-01', c.user_id
FROM _vv_seed_ctx c
JOIN _vv_lists l ON l.key = 'reparto'
ON CONFLICT DO NOTHING;

INSERT INTO rate_components (id, organization_id, branch_id, set_id, code, label, percentage, calculation_base,
                             component_order)
SELECT md5('vaca-verde:rate-component:reparto:' || v.code)::uuid, c.organization_id, c.branch_id, s.id, v.code, v.label,
       v.percentage::numeric(9,4), 'Base', v.component_order
FROM (VALUES
    ('IVA', 'IVA (10,5%)', '10.5', 1),
    ('IB', 'Ingresos Brutos (2,5%)', '2.5', 2),
    ('FLETE', 'Flete (7%)', '7', 3),
    ('REMARCACION', 'Remarcación (25%)', '25', 4)
) AS v (code, label, percentage, component_order)
CROSS JOIN _vv_seed_ctx c
JOIN rate_component_sets s ON s.organization_id = c.organization_id AND s.branch_id = c.branch_id
                          AND s.id = md5('vaca-verde:rate-set:reparto:2026-10-01')::uuid
ON CONFLICT DO NOTHING;


COMMIT;
