# -*- coding: utf-8 -*-
"""Generate 001_vaca_verde_master_data.sql from the JSON written by normalize.py.

Usage:
    python generate_seed.py --data-dir build [--out 001_vaca_verde_master_data.sql]

The SQL is deterministic: the same JSON always yields the same bytes.
"""
import argparse
import json
import os
import re
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))


def q(v):
    """SQL literal: NULL or a single-quoted string (standard_conforming_strings is on)."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def slug(s):
    s = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def load(data_dir, name):
    with open(os.path.join(data_dir, name), encoding="utf-8") as f:
        return json.load(f)


def values(rows):
    return ",\n".join("    (" + ", ".join(r) + ")" for r in rows)


HEADER = """-- Vaca Verde master data seed: cities, business types and customers.
--
-- GENERATED by generate_seed.py from the normalized spreadsheets - do not edit
-- by hand; see README.md in this directory. Contains REAL customer data (owner
-- decision), applied after the organization is provisioned.
--
-- Safe to re-run: every row has a deterministic id and is inserted with
-- ON CONFLICT DO NOTHING, so a second run changes nothing and never overwrites
-- later edits. When the organization "Vaca Verde" (or its business admin) does
-- not exist yet, the file prints a NOTICE and changes nothing.
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 001_vaca_verde_master_data.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the customers.';
        RETURN;
    END IF;

    INSERT INTO _vv_seed_ctx (organization_id, user_id) VALUES (v_org, v_user);
END $$;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-dir", default="build", help="directory with cities.json, business_types.json, customers.json")
    ap.add_argument("--out", default=os.path.join(HERE, "001_vaca_verde_master_data.sql"))
    a = ap.parse_args()

    cities = load(a.data_dir, "cities.json")
    types = load(a.data_dir, "business_types.json")
    customers = load(a.data_dir, "customers.json")

    out = [HEADER]

    out.append("-- Cities: the 23 reference rows keep their original id and audit dates;")
    out.append("-- new ones get a deterministic id and the current time.")
    rows = [[q(c["id"]), q(c["name"]), q(c["key"]), str(c["sortOrder"]), q("true" if c["isActive"] else "false"),
             q(c["createdAt"]), q(c["updatedAt"])] for c in cities]
    out.append(f"""INSERT INTO cities (id, organization_id, name, key, sort_order, is_active, created_at_utc, updated_at_utc)
SELECT COALESCE(v.id::uuid, md5('vaca-verde:city:' || v.key)::uuid), c.organization_id, v.name, v.key,
       v.sort_order::integer, v.is_active::boolean,
       COALESCE(v.created_at::timestamptz, now()), COALESCE(v.updated_at::timestamptz, now())
FROM (VALUES
{values(rows)}
) AS v (id, name, key, sort_order, is_active, created_at, updated_at)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;
""")

    out.append("-- Business types.")
    rows = [[q(t["name"]), q(t["key"]), q(str(t["sortOrder"]))] for t in types]
    out.append(f"""INSERT INTO business_types (id, organization_id, name, key, sort_order)
SELECT md5('vaca-verde:business-type:' || v.key)::uuid, c.organization_id, v.name, v.key, v.sort_order::integer
FROM (VALUES
{values(rows)}
) AS v (name, key, sort_order)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;
""")

    out.append("-- Customers (Wholesale, enabled). The id derives from `key` (name + city slug).")
    keys = set()
    rows = []
    for cu in customers:
        key = slug(cu["displayName"]) + ("--" + cu["cityKey"] if cu["cityKey"] else "")
        assert key not in keys, f"duplicate customer key {key}"
        keys.add(key)
        rows.append([q(key), q(cu["displayName"]), q(cu["contactName"]), q(cu["addressStreet"]), q(cu["phone"]),
                     q(cu["cityKey"]), q(cu["businessTypeKey"]), q(cu["taxIdType"]), q(cu["taxId"]), q(cu["notes"])])
    out.append(f"""INSERT INTO customers (id, organization_id, customer_kind, display_name, contact_name, address_street, phone,
                       city_id, business_type_id, tax_id_type, tax_id, notes, is_enabled, created_by_user_id)
SELECT md5('vaca-verde:customer:' || v.key)::uuid, c.organization_id, 'Wholesale', v.display_name, v.contact_name,
       v.address_street, v.phone, ci.id, bt.id, v.tax_id_type, v.tax_id, v.notes, true, c.user_id
FROM (VALUES
{values(rows)}
) AS v (key, display_name, contact_name, address_street, phone, city_key, business_type_key, tax_id_type, tax_id, notes)
CROSS JOIN _vv_seed_ctx c
LEFT JOIN cities ci ON ci.organization_id = c.organization_id AND ci.key = v.city_key
LEFT JOIN business_types bt ON bt.organization_id = c.organization_id AND bt.key = v.business_type_key
ON CONFLICT DO NOTHING;

COMMIT;
""")

    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {a.out}: {len(cities)} cities, {len(types)} business types, {len(customers)} customers")


if __name__ == "__main__":
    main()
