# -*- coding: utf-8 -*-
"""Generate 001_vaca_verde_master_data.sql from the JSON written by normalize.py.

Usage:
    python generate_seed.py --data-dir build [--out 001_vaca_verde_master_data.sql]

The SQL is deterministic: the same JSON always yields the same bytes.
"""
import argparse
import json
import os
import re
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))

# Cities are global core geography since migration 0028: the seed no longer
# creates them, it points customers at the Georef locality (INDEC id) that
# matches each of the owner's city keys. Same decisions as the migration's
# mapping of the old organization cities (None = no Georef locality: Doyle is
# "Pueblo Doyle" in Georef, Urquiza is ambiguous; both stay unmapped).
CITY_INDEC = {
    "arrecifes": "06077010",
    "arroyo_dulce": "06714010",
    "baradero": "06070010",
    "capital_federal": "02014010",        # Ciudad de Buenos Aires
    "capitan_sarmiento": "06140010",
    "carmen_de_areco": "06161010",
    "chacabuco": "06210020",
    "cordoba": "14014010",
    "doyle": None,
    "ines_indart": "06714040",
    "la_plata": "06441030",
    "perez_millan": "06665030",
    "pergamino": "06623100",
    "ramallo": "06665040",
    "rio_tala": "06770040",
    "rojas": "06686060",
    "salto": "06714060",
    "san_andres_de_giles": "06728040",
    "san_antonio_de_areco": "06735020",
    "san_nicolas": "06763050",            # San Nicolás de los Arroyos
    "san_pedro": "06770050",
    "santa_lucia": "06770060",
    "santiago_del_estero": "86049110",
    "urquiza": None,
    "zarate": "06882050",
}


def q(v):
    """SQL literal: NULL or a single-quoted string (standard_conforming_strings is on)."""
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def slug(s):
    s = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def customer_key(cu):
    return slug(cu["displayName"]) + ("--" + cu["cityKey"] if cu["cityKey"] else "")


def load(data_dir, name):
    with open(os.path.join(data_dir, name), encoding="utf-8") as f:
        return json.load(f)


def values(rows):
    return ",\n".join("    (" + ", ".join(r) + ")" for r in rows)


HEADER = """-- Vaca Verde master data seed: business types, customers and their contacts.
--
-- GENERATED by generate_seed.py from the normalized spreadsheets - do not edit
-- by hand; see README.md in this directory. Contains REAL customer data (owner
-- decision), applied after the organization is provisioned.
--
-- Cities are NOT created here: they are global core geography (migration 0028,
-- Georef). Customers reference a Georef locality by its INDEC id, and the
-- original audit dates of the owner's cities are restored on those global rows
-- when nobody has touched them since they were loaded.
--
-- Safe to re-run: every row has a deterministic id and is inserted with
-- ON CONFLICT DO NOTHING, so a second run changes nothing and never overwrites
-- later edits. When the organization "Vaca Verde" (or its business admin) does
-- not exist yet, the file prints a NOTICE and changes nothing.
--
-- Run as the database owner, e.g.:
--   psql -U commerce_owner -d <db> -v ON_ERROR_STOP=1 -f 001_vaca_verde_master_data.sql
-- If the owner role is subject to row level security, scope the session to the
-- organization first: PGOPTIONS="-c app.current_org_id=<organization uuid>".

SET client_encoding = 'UTF8';

BEGIN;

CREATE TEMP TABLE _vv_seed_ctx (organization_id uuid NOT NULL, user_id uuid NOT NULL) ON COMMIT DROP;

DO $$
DECLARE
    v_scope uuid := NULLIF(current_setting('app.current_org_id', true), '')::uuid;
    v_org   uuid;
    v_user  uuid;
BEGIN
    SELECT id INTO v_org
    FROM organizations
    WHERE lower(btrim(name)) = 'vaca verde' AND (v_scope IS NULL OR id = v_scope)
    ORDER BY created_at, id
    LIMIT 1;

    IF v_org IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: organization "Vaca Verde" not found (provision it first; under row level security set app.current_org_id).';
        RETURN;
    END IF;

    -- Row level security is keyed on this setting; transaction-local.
    PERFORM set_config('app.current_org_id', v_org::text, true);

    SELECT id INTO v_user
    FROM users
    WHERE organization_id = v_org
      AND NOT is_revoked
      AND customer_id IS NULL
      AND roles @> '[{"name":"business-admin"}]'::jsonb
    ORDER BY created_at_utc, id
    LIMIT 1;

    IF v_user IS NULL THEN
        RAISE NOTICE 'Vaca Verde seed skipped: the organization has no business-admin user to own the customers.';
        RETURN;
    END IF;

    INSERT INTO _vv_seed_ctx (organization_id, user_id) VALUES (v_org, v_user);
END $$;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-dir", default="build", help="directory with cities.json (audit dates), business_types.json, customers.json")
    ap.add_argument("--out", default=os.path.join(HERE, "001_vaca_verde_master_data.sql"))
    a = ap.parse_args()

    cities = load(a.data_dir, "cities.json")
    types = load(a.data_dir, "business_types.json")
    customers = load(a.data_dir, "customers.json")

    out = [HEADER]

    out.append("-- Cities are global (Georef, migration 0028). Restore the owner's original audit dates")
    out.append("-- on the matching rows, only while they still carry the load time (never over later edits).")
    rows = []
    for c in cities:
        indec = CITY_INDEC[c["key"]]
        if indec and c["createdAt"] and c["updatedAt"]:
            rows.append([q(indec), q(c["createdAt"]), q(c["updatedAt"])])
    out.append(f"""UPDATE cities g
SET created_at_utc = v.created_at::timestamptz, updated_at_utc = v.updated_at::timestamptz
FROM (VALUES
{values(rows)}
) AS v (indec_id, created_at, updated_at)
WHERE g.indec_id = v.indec_id
  AND g.updated_at_utc = g.created_at_utc
  AND g.created_at_utc > v.created_at::timestamptz
  AND EXISTS (SELECT 1 FROM _vv_seed_ctx);
""")

    out.append("-- Business types.")
    rows = [[q(t["name"]), q(t["key"]), q(str(t["sortOrder"]))] for t in types]
    out.append(f"""INSERT INTO business_types (id, organization_id, name, key, sort_order)
SELECT md5('vaca-verde:business-type:' || v.key)::uuid, c.organization_id, v.name, v.key, v.sort_order::integer
FROM (VALUES
{values(rows)}
) AS v (name, key, sort_order)
CROSS JOIN _vv_seed_ctx c
ON CONFLICT DO NOTHING;
""")

    out.append("-- Customers (Wholesale, enabled). The id derives from `key` (name + city slug).")
    keys = set()
    rows = []
    for cu in customers:
        key = customer_key(cu)
        assert key not in keys, f"duplicate customer key {key}"
        keys.add(key)
        rows.append([q(key), q(cu["displayName"]), q(cu["addressStreet"]), q(cu["phone"]),
                     q(CITY_INDEC[cu["cityKey"]] if cu["cityKey"] else None), q(cu["businessTypeKey"]),
                     q(cu["taxIdType"]), q(cu["taxId"]), q(cu["notes"])])
    out.append(f"""INSERT INTO customers (id, organization_id, customer_kind, display_name, address_street, phone,
                       city_id, business_type_id, tax_id_type, tax_id, notes, is_enabled, created_by_user_id)
SELECT md5('vaca-verde:customer:' || v.key)::uuid, c.organization_id, 'Wholesale', v.display_name,
       v.address_street, v.phone, ci.id, bt.id, v.tax_id_type, v.tax_id, v.notes, true, c.user_id
FROM (VALUES
{values(rows)}
) AS v (key, display_name, address_street, phone, city_indec_id, business_type_key, tax_id_type, tax_id, notes)
CROSS JOIN _vv_seed_ctx c
LEFT JOIN cities ci ON ci.indec_id = v.city_indec_id
LEFT JOIN business_types bt ON bt.organization_id = c.organization_id AND bt.key = v.business_type_key
ON CONFLICT DO NOTHING;
""")

    # Contacts: the CLIENTE column. "Lucas Badano" (exactly two words) is split into first and last
    # name; anything else stays whole in first_name. Each one is the customer's primary contact.
    rows = []
    for cu in customers:
        raw = cu["contactName"]
        if not raw:
            continue
        key = customer_key(cu)
        words = raw.split()
        first, last = (words[0], words[1]) if len(words) == 2 else (raw, None)
        rows.append([q(key), q(first), q(last), q(raw)])
    out.append("-- Contacts: the CLIENTE column as each customer's primary contact (id derives from the customer key).")
    out.append(f"""INSERT INTO customer_contacts (id, organization_id, customer_id, first_name, last_name, is_primary)
SELECT md5('vaca-verde:contact:' || v.key)::uuid, c.organization_id, md5('vaca-verde:customer:' || v.key)::uuid,
       v.first_name, v.last_name, true
FROM (VALUES
{values(rows)}
) AS v (key, first_name, last_name, raw_name)
CROSS JOIN _vv_seed_ctx c
WHERE EXISTS (SELECT 1 FROM customers cu
              WHERE cu.organization_id = c.organization_id AND cu.id = md5('vaca-verde:customer:' || v.key)::uuid)
ON CONFLICT DO NOTHING;

-- A contact migrated from the old single `contact_name` column (migration 0029) holds the whole text in
-- first_name: split it the same way, only while nobody has edited it since.
UPDATE customer_contacts cc
SET first_name = v.first_name, last_name = v.last_name
FROM (VALUES
{values([r for r in rows if r[2] != "NULL"])}
) AS v (key, first_name, last_name, raw_name)
CROSS JOIN _vv_seed_ctx c
WHERE cc.organization_id = c.organization_id
  AND cc.customer_id = md5('vaca-verde:customer:' || v.key)::uuid
  AND cc.first_name = v.raw_name AND cc.last_name IS NULL
  AND cc.updated_at_utc = cc.created_at_utc;

COMMIT;
""")

    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {a.out}: {len(types)} business types, {len(customers)} customers, "
          f"{sum(1 for c in customers if c['contactName'])} contacts")


if __name__ == "__main__":
    main()
